USE [master]
GO

/****** Object:  Database [RecipesDemoDB]    Script Date: 7/18/2025 6:15:53 AM ******/
CREATE DATABASE [RecipesDemoDB]
	CONTAINMENT = NONE
ON PRIMARY ( 
	NAME = N'RecipesDemoDB', 
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\RecipesDemoDB.mdf', 
	SIZE = 2969600KB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 51200KB 
), 
FILEGROUP [VECTOR_FG] (
	NAME = N'RecipesDemoDB_VectorData', 
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\RecipesDemoDB_VectorData.ndf', 
	SIZE = 45092352KB, 
	MAXSIZE = UNLIMITED, 
	FILEGROWTH = 51200KB 
)
LOG ON ( 
	NAME = N'RecipesDemoDB_log', 
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\RecipesDemoDB_log.ldf', 
	SIZE = 24432640KB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 65536KB 
)
WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [RecipesDemoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecipesDemoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecipesDemoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecipesDemoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RecipesDemoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecipesDemoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RecipesDemoDB] SET  MULTI_USER 
GO

ALTER DATABASE [RecipesDemoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecipesDemoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecipesDemoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecipesDemoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RecipesDemoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RecipesDemoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RecipesDemoDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [RecipesDemoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RecipesDemoDB] SET  READ_WRITE 
GO


